---

- name: Ensure GlusterFS server is started and enabled at boot
  service:
    name: glusterd
    state: started
    enabled: yes

- name: create gluster cluster
  command: gluster peer probe {{ item }}.{{dns_domain}}
  with_items:
    - "{{ (groups[gluster_group_name]|difference([inventory_hostname])) }}"
  when: inventory_hostname == gluster_master
  ignore_errors: True

- name: check gluster cluster status
  command: gluster peer status
  register: gluster_status

- name: create gluster volume
  glusterfs_volume:
    state: present
    name: "{{ item.name }}"
    brick: "{{ item.brick |join(',')}}"
    replicas: "{{ item.replicas }}"
    cluster: "{% for host in groups[gluster_group_name] %}{{ host }}.{{dns_domain}}{% if not loop.last %},{% endif %}{% endfor %}"
  with_items:
    - glusterfs_volumes
  when: inventory_hostname == gluster_master
  tags:
    - create_volumes
