---

- name: Ensure GlusterFS server is started and enabled at boot
  service:
    name: glusterd
    state: started
    enabled: yes

- name: create bricks on arbiters
  file:
    path: "{{ mount_point }}{{ item.brick_name }}"
    owner: root
    group: root
    state: directory
  with_items: gluster_bricks
  when: inventory_hostname in groups[glusterfs_arbiter_group]

- name: create gluster cluster
  command: gluster peer probe {{ item }}.{{dns_domain}}
  with_items:
    - "{{ (groups[glusterfs_server_group]|difference([inventory_hostname])) }}"
  delegate_to: gluster_master
  ignore_errors: True

- name: check gluster cluster status
  command: gluster peer status
  register: gluster_status

#- name: set fact bricks path
#  set_fact:
#    bricks_items: "{{mount_point}}{{ item.brick_name }}"
#  with_items: gluster_bricks
#  register: bricks_result
#  tags: bricks_list
#
#- name: make a list
#  set_fact:
#    bricks_paths: "{{ bricks_result.results | map(attribute='ansible_facts.bricks_items') | list }}"
#  with_items: bricks_result
#  tags: bricks_list
#
#- debug: var=bricks_paths
#  tags: bricks_list

- name: create gluster volume
  glusterfs_volumes:
    state: present
    name: "{{ item.name }}"
    brick: "{{ item.brick |join(',')}}"
    force: "{{ item.force|default('False') }}"
    replicas: "{{ item.replicas }}"
    cluster: "{% for host in groups[glusterfs_server_group] %}{{ host }}.{{dns_domain}}{% if not loop.last %},{% endif %}{% endfor %}"
  with_items: glusterfs_volumes
  delegate_to: gluster_master
  tags:
    - create_volumes
