---

- name: Ensure GlusterFS server is started and enabled at boot
  service:
    name: glusterd
    state: started
    enabled: yes

# TODO: Tem que melhorar isso
- name: create gluster cluster
  command: gluster probe {{ item }}
  with_items: gluster_members
  when: inventory_hostname == gluster_master

- name: check gluster cluster status
  command: gluster peer status
  register: gluster_status

- debug: var=gluster_status
  when: gluster_status is defined

- name: Create GlusterFS volumes
  gluster_volume:
    name: "{{ item.name }}"
    replicas: "{{ item.replicas|default(omit) }}"
    cluster: "{{ item.cluster|default(omit) }}"
    start_on_create: "{{ item.start_on_create|default('yes') }}"
    brick: '{{ item.bricks | join(",") }}'
    state: "{{ item.state|default('present') }}"
#    force: "{{ item.force }}"
#    host: "{{ item.host|default(omit) }}"
#    transport: "{{ item.transport|default('tcp') }}"
#    quota: "{{ item.quota|default(omit) }}"
#    rebalance: "{{ item.rebalance|default('no') }}"
#    stripes: "{{ item.stripes|default(omit) }}"
#    options: "{{ item.options|default(omit) }}"
#    directory: "{{ item.directory|default(omit) }}"
  with_items: glusterfs_volumes
  when: inventory_hostname == gluster_master
  run_once: true
