---

- name: SERVER - start and enable firewalld service
  service:
    name: firewalld
    enabled: yes
    state: started

- name: SERVER - set firewalld rule to mountd and high-availability
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: True
  with_items:
    - mountd
    - high-availability
  when: glusterfs_install_server

- name: SERVER - set firewalld rule to gluster ports
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: True
    immediate: True
  with_items:
    - 4501/tcp
    - 4501/udp
    - 32803/tcp
    - 32803/udp
    - 662/tcp
    - 662/udp
    - 24007/tcp
    - 24007/udp
  when: glusterfs_install_server

- name: CLIENT - set firewalld rule to gluster ports
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: True
    immediate: True
  with_items:
    - 662/tcp
    - 662/udp
    - 32803/tcp
    - 32769/udp
    - 892/tcp
    - 892/udp
  when: glusterfs_install_client
