---

- name: include lvm reset
  include: reset.yml
  when: reset_lvm
  tags:
    - reset_lvm

- name: create gluster pv
  command: pvcreate --dataalignment {{item.pv_dataalignment |default('1280')}}K {{ item.disk }}
  with_items: pv_disks

- name: create gluster vg
  command: vgcreate --physicalextentsize {{ item.vg_extentsize }}K {{ item.vg_name }} {{ item.disk }}
  with_items: pv_disks

- name: create thin provisioning pool
  command: lvcreate --thinpool {{item.vg_name}}/{{item.thin_name}} --size 5M --chunksize {{item.lv_chunk}}K --poolmetadatasize {{item.lv_metadatasize}}
  with_items: pv_disks

- name: extend thin pool
  command: lvextend {{item.vg_name}}/{{item.thin_name}} --extents 100%VG
  with_items: pv_disks

- name: create gluster bricks
  command: lvcreate --thin --name {{ item.brick_name }} --virtualsize {{ item.virtualsize }} {{ item.vg_name }}/{{item.thin_name}}
  with_items: gluster_bricks

- name: format logical volumes
  filesystem:
    dev: "/dev/{{ item.vg_name }}/{{item.brick_name}}"
    force: True
    fstype: xfs
    opts: "{{ mkfs_options_xfs }}"
  with_items: gluster_bricks

- name: mount bricks devices
  mount:
    src: "/dev/mapper/{{item.vg_name}}-{{item.brick_name}}"
    name: "{{ mount_point }}{{ item.brick_name }}"
    fstype: xfs
    opts: "{{ mount_options_xfs }}"
    state: mounted
  with_items: gluster_bricks

#mkfs.xfs -f -i size=512 -n size=8192 -d su=128k,sw=1 /dev/mapper/vg1-brick1