---

- name: unmount bricks devices
  mount:
    src: "/dev/mapper/{{item.vg_name}}-{{item.brick_name}}"
    name: "{{ mount_point }}{{ item.brick_name }}"
    opts: "{{ mount_options_xfs }}"
    state: absent
    fstype: xfs
  with_items: gluster_bricks
  ignore_errors: True

- name: remove vgs
  command: vgremove -ff {{ item.vg_name }}
  with_items: pv_disks
  ignore_errors: True

- name: remove pvs
  command: pvremove -ff {{ item.disk }}
  with_items: pv_disks
  ignore_errors: True
